"""Create users table

Revision ID: 2e11199ac40b
Revises: 
Create Date: 2023-04-30 19:21:30.677198

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "2e11199ac40b"
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "users",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("username", sa.String(), nullable=True),
        sa.Column("password", sa.String(), nullable=True),
        sa.Column(
            "is_active", sa.Boolean(), server_default="t", nullable=True
        ),
        sa.Column(
            "is_superuser", sa.Boolean(), server_default="f", nullable=True
        ),
        sa.Column(
            "is_verified", sa.Boolean(), server_default="f", nullable=True
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("users")
    # ### end Alembic commands ###
