version: "3.1"

services:
  pb:
    build:
      dockerfile: ./pb.Dockerfile
    ports:
      - 8080:8080
    volumes:
      - pb_data:/pb/pb_data

  redis:
    image: redis/redis-stack-server:6.2.6-v7
    restart: always
    ports:
      - 6379:6379
    volumes:
      - redis_data:/local-data/

  mailhog:
    image: mailhog/mailhog:v1.0.1
    ports:
      - 1025:1025
      - 8025:8025

volumes:
  redis_data:
  pb_data:
