version: "3.1"

services:
  postgres:
    image: postgres:15-alpine
    restart: always
    ports:
      - 5432:5432
    volumes:
      - pg_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_USERNAME=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=chatappdb

  adminer:
    image: adminer
    restart: always
    ports:
      - 5433:8080
    environment:
      # - ADMINER_PLUGINS='tables-filter tinymce'
      - ADMINER_DESIGN=galkaev

  redis:
    image: redis/redis-stack-server:6.2.6-v7
    restart: always
    ports:
      - 6379:6379
    volumes:
      - redis_data:/local-data/

  mailhog:
    image: mailhog/mailhog:v1.0.1
    ports:
      - 1025:1025
      - 1026:8025

volumes:
  redis_data:
  pg_data:
